[mypy]
python_version = 3.12
files = medivox_shim
check_untyped_defs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True

[mypy-sounddevice.*]
ignore_missing_imports = True

[mypy-pystray.*]
ignore_missing_imports = True
